package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Baohanh generated by hbm2java
 */
@Entity
@Table(name = "baohanh", catalog = "dienthoai")
public class Baohanh implements java.io.Serializable {

	private Integer idBaohanh;
	private String loaiBaohanh;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public Baohanh() {
	}

	public Baohanh(String loaiBaohanh) {
		this.loaiBaohanh = loaiBaohanh;
	}

	public Baohanh(String loaiBaohanh, Set<Chitietdt> chitietdts) {
		this.loaiBaohanh = loaiBaohanh;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_baohanh", unique = true, nullable = false)
	public Integer getIdBaohanh() {
		return this.idBaohanh;
	}

	public void setIdBaohanh(Integer idBaohanh) {
		this.idBaohanh = idBaohanh;
	}

	@Column(name = "loai_baohanh", nullable = false, length = 50)
	public String getLoaiBaohanh() {
		return this.loaiBaohanh;
	}

	public void setLoaiBaohanh(String loaiBaohanh) {
		this.loaiBaohanh = loaiBaohanh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "baohanh")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
