package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Binhluan generated by hbm2java
 */
@Entity
@Table(name = "binhluan", catalog = "dienthoai")
public class Binhluan implements java.io.Serializable {

	private Integer idBinhluan;
	private Dienthoai dienthoai;
	private String tenKhachhangbl;
	private String gmail;
	private String noidung;
	private Date thoigian;
	private Set<TraloiBl> traloiBls = new HashSet<TraloiBl>(0);

	public Binhluan() {
	}

	public Binhluan(Dienthoai dienthoai, String tenKhachhangbl, String gmail, String noidung, Date thoigian) {
		this.dienthoai = dienthoai;
		this.tenKhachhangbl = tenKhachhangbl;
		this.gmail = gmail;
		this.noidung = noidung;
		this.thoigian = thoigian;
	}

	public Binhluan(Dienthoai dienthoai, String tenKhachhangbl, String gmail, String noidung, Date thoigian,
			Set<TraloiBl> traloiBls) {
		this.dienthoai = dienthoai;
		this.tenKhachhangbl = tenKhachhangbl;
		this.gmail = gmail;
		this.noidung = noidung;
		this.thoigian = thoigian;
		this.traloiBls = traloiBls;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_binhluan", unique = true, nullable = false)
	public Integer getIdBinhluan() {
		return this.idBinhluan;
	}

	public void setIdBinhluan(Integer idBinhluan) {
		this.idBinhluan = idBinhluan;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dt", nullable = false)
	public Dienthoai getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(Dienthoai dienthoai) {
		this.dienthoai = dienthoai;
	}

	@Column(name = "ten_khachhangbl", nullable = false, length = 100)
	public String getTenKhachhangbl() {
		return this.tenKhachhangbl;
	}

	public void setTenKhachhangbl(String tenKhachhangbl) {
		this.tenKhachhangbl = tenKhachhangbl;
	}

	@Column(name = "gmail", nullable = false, length = 100)
	public String getGmail() {
		return this.gmail;
	}

	public void setGmail(String gmail) {
		this.gmail = gmail;
	}

	@Column(name = "noidung", nullable = false, length = 200)
	public String getNoidung() {
		return this.noidung;
	}

	public void setNoidung(String noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thoigian", nullable = false, length = 19)
	public Date getThoigian() {
		return this.thoigian;
	}

	public void setThoigian(Date thoigian) {
		this.thoigian = thoigian;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "binhluan")
	public Set<TraloiBl> getTraloiBls() {
		return this.traloiBls;
	}

	public void setTraloiBls(Set<TraloiBl> traloiBls) {
		this.traloiBls = traloiBls;
	}

}
