package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BonhoLuutru generated by hbm2java
 */
@Entity
@Table(name = "bonho_luutru", catalog = "dienthoai")
public class BonhoLuutru implements java.io.Serializable {

	private int idBonhoLuutru;
	private String danhba;
	private String rom;
	private String bonho;
	private String thenhongoai;
	private String hotrothe;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public BonhoLuutru() {
	}

	public BonhoLuutru(int idBonhoLuutru, String danhba, String rom, String bonho, String thenhongoai,
			String hotrothe) {
		this.idBonhoLuutru = idBonhoLuutru;
		this.danhba = danhba;
		this.rom = rom;
		this.bonho = bonho;
		this.thenhongoai = thenhongoai;
		this.hotrothe = hotrothe;
	}

	public BonhoLuutru(int idBonhoLuutru, String danhba, String rom, String bonho, String thenhongoai, String hotrothe,
			Set<Chitietdt> chitietdts) {
		this.idBonhoLuutru = idBonhoLuutru;
		this.danhba = danhba;
		this.rom = rom;
		this.bonho = bonho;
		this.thenhongoai = thenhongoai;
		this.hotrothe = hotrothe;
		this.chitietdts = chitietdts;
	}

	@Id

	@Column(name = "id_bonho_luutru", unique = true, nullable = false)
	public int getIdBonhoLuutru() {
		return this.idBonhoLuutru;
	}

	public void setIdBonhoLuutru(int idBonhoLuutru) {
		this.idBonhoLuutru = idBonhoLuutru;
	}

	@Column(name = "danhba", nullable = false, length = 50)
	public String getDanhba() {
		return this.danhba;
	}

	public void setDanhba(String danhba) {
		this.danhba = danhba;
	}

	@Column(name = "rom", nullable = false, length = 50)
	public String getRom() {
		return this.rom;
	}

	public void setRom(String rom) {
		this.rom = rom;
	}

	@Column(name = "bonho", nullable = false, length = 50)
	public String getBonho() {
		return this.bonho;
	}

	public void setBonho(String bonho) {
		this.bonho = bonho;
	}

	@Column(name = "thenhongoai", nullable = false, length = 50)
	public String getThenhongoai() {
		return this.thenhongoai;
	}

	public void setThenhongoai(String thenhongoai) {
		this.thenhongoai = thenhongoai;
	}

	@Column(name = "hotrothe", nullable = false, length = 50)
	public String getHotrothe() {
		return this.hotrothe;
	}

	public void setHotrothe(String hotrothe) {
		this.hotrothe = hotrothe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bonhoLuutru")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
