package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitietkm generated by hbm2java
 */
@Entity
@Table(name = "chitietkm", catalog = "dienthoai")
public class Chitietkm implements java.io.Serializable {

	private Integer idChitietkm;
	private Dienthoai dienthoai;
	private Khuyenmai khuyenmai;
	private String giagiam;

	public Chitietkm() {
	}

	public Chitietkm(Dienthoai dienthoai, Khuyenmai khuyenmai, String giagiam) {
		this.dienthoai = dienthoai;
		this.khuyenmai = khuyenmai;
		this.giagiam = giagiam;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chitietkm", unique = true, nullable = false)
	public Integer getIdChitietkm() {
		return this.idChitietkm;
	}

	public void setIdChitietkm(Integer idChitietkm) {
		this.idChitietkm = idChitietkm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dienthoai", nullable = false)
	public Dienthoai getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(Dienthoai dienthoai) {
		this.dienthoai = dienthoai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_km", nullable = false)
	public Khuyenmai getKhuyenmai() {
		return this.khuyenmai;
	}

	public void setKhuyenmai(Khuyenmai khuyenmai) {
		this.khuyenmai = khuyenmai;
	}

	@Column(name = "giagiam", nullable = false, length = 200)
	public String getGiagiam() {
		return this.giagiam;
	}

	public void setGiagiam(String giagiam) {
		this.giagiam = giagiam;
	}

}
