package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Chitiethoadon generated by hbm2java
 */
@Entity
@Table(name = "chitiethoadon", catalog = "dienthoai")
public class Chitiethoadon implements java.io.Serializable {

	private Integer idChitiethd;
	private Dienthoai dienthoai;
	private Hoadon hoadon;
	private int soluong;
	private String dongia;

	public Chitiethoadon() {
	}

	public Chitiethoadon(Dienthoai dienthoai, Hoadon hoadon, int soluong, String dongia) {
		this.dienthoai = dienthoai;
		this.hoadon = hoadon;
		this.soluong = soluong;
		this.dongia = dongia;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chitiethd", unique = true, nullable = false)
	public Integer getIdChitiethd() {
		return this.idChitiethd;
	}

	public void setIdChitiethd(Integer idChitiethd) {
		this.idChitiethd = idChitiethd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dienthoai", nullable = false)
	public Dienthoai getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(Dienthoai dienthoai) {
		this.dienthoai = dienthoai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hoadon", nullable = false)
	public Hoadon getHoadon() {
		return this.hoadon;
	}

	public void setHoadon(Hoadon hoadon) {
		this.hoadon = hoadon;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Column(name = "dongia", nullable = false, length = 100)
	public String getDongia() {
		return this.dongia;
	}

	public void setDongia(String dongia) {
		this.dongia = dongia;
	}

}
