package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Chitietdt generated by hbm2java
 */
@Entity
@Table(name = "chitietdt", catalog = "dienthoai")
public class Chitietdt implements java.io.Serializable {

	private Integer idChitiet;
	private Baohanh baohanh;
	private BonhoLuutru bonhoLuutru;
	private Camera camera;
	private Cauhinhphancung cauhinhphancung;
	private Dienthoai dienthoai;
	private GiaitriUngdung giaitriUngdung;
	private Hedieuhanh hedieuhanh;
	private KetnoiCong ketnoiCong;
	private Manhinh manhinh;
	private ThietkeTrongluong thietkeTrongluong;
	private Thongtinpin thongtinpin;
	private int soluong;
	private Date ngaynhap;

	public Chitietdt() {
	}

	public Chitietdt(Baohanh baohanh, BonhoLuutru bonhoLuutru, Camera camera, Cauhinhphancung cauhinhphancung,
			Dienthoai dienthoai, GiaitriUngdung giaitriUngdung, Hedieuhanh hedieuhanh, KetnoiCong ketnoiCong,
			Manhinh manhinh, ThietkeTrongluong thietkeTrongluong, Thongtinpin thongtinpin, int soluong, Date ngaynhap) {
		this.baohanh = baohanh;
		this.bonhoLuutru = bonhoLuutru;
		this.camera = camera;
		this.cauhinhphancung = cauhinhphancung;
		this.dienthoai = dienthoai;
		this.giaitriUngdung = giaitriUngdung;
		this.hedieuhanh = hedieuhanh;
		this.ketnoiCong = ketnoiCong;
		this.manhinh = manhinh;
		this.thietkeTrongluong = thietkeTrongluong;
		this.thongtinpin = thongtinpin;
		this.soluong = soluong;
		this.ngaynhap = ngaynhap;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_chitiet", unique = true, nullable = false)
	public Integer getIdChitiet() {
		return this.idChitiet;
	}

	public void setIdChitiet(Integer idChitiet) {
		this.idChitiet = idChitiet;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_baohanh", nullable = false)
	public Baohanh getBaohanh() {
		return this.baohanh;
	}

	public void setBaohanh(Baohanh baohanh) {
		this.baohanh = baohanh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_bonho_luutru", nullable = false)
	public BonhoLuutru getBonhoLuutru() {
		return this.bonhoLuutru;
	}

	public void setBonhoLuutru(BonhoLuutru bonhoLuutru) {
		this.bonhoLuutru = bonhoLuutru;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_camera", nullable = false)
	public Camera getCamera() {
		return this.camera;
	}

	public void setCamera(Camera camera) {
		this.camera = camera;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_cauhinhphancung", nullable = false)
	public Cauhinhphancung getCauhinhphancung() {
		return this.cauhinhphancung;
	}

	public void setCauhinhphancung(Cauhinhphancung cauhinhphancung) {
		this.cauhinhphancung = cauhinhphancung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dienthoai", nullable = false)
	public Dienthoai getDienthoai() {
		return this.dienthoai;
	}

	public void setDienthoai(Dienthoai dienthoai) {
		this.dienthoai = dienthoai;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_giaitri_ungdung", nullable = false)
	public GiaitriUngdung getGiaitriUngdung() {
		return this.giaitriUngdung;
	}

	public void setGiaitriUngdung(GiaitriUngdung giaitriUngdung) {
		this.giaitriUngdung = giaitriUngdung;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hdh", nullable = false)
	public Hedieuhanh getHedieuhanh() {
		return this.hedieuhanh;
	}

	public void setHedieuhanh(Hedieuhanh hedieuhanh) {
		this.hedieuhanh = hedieuhanh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_ketnoi_cong", nullable = false)
	public KetnoiCong getKetnoiCong() {
		return this.ketnoiCong;
	}

	public void setKetnoiCong(KetnoiCong ketnoiCong) {
		this.ketnoiCong = ketnoiCong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_manhinh", nullable = false)
	public Manhinh getManhinh() {
		return this.manhinh;
	}

	public void setManhinh(Manhinh manhinh) {
		this.manhinh = manhinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_thietke_trongluong", nullable = false)
	public ThietkeTrongluong getThietkeTrongluong() {
		return this.thietkeTrongluong;
	}

	public void setThietkeTrongluong(ThietkeTrongluong thietkeTrongluong) {
		this.thietkeTrongluong = thietkeTrongluong;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_thongtinpin", nullable = false)
	public Thongtinpin getThongtinpin() {
		return this.thongtinpin;
	}

	public void setThongtinpin(Thongtinpin thongtinpin) {
		this.thongtinpin = thongtinpin;
	}

	@Column(name = "soluong", nullable = false)
	public int getSoluong() {
		return this.soluong;
	}

	public void setSoluong(int soluong) {
		this.soluong = soluong;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaynhap", nullable = false, length = 10)
	public Date getNgaynhap() {
		return this.ngaynhap;
	}

	public void setNgaynhap(Date ngaynhap) {
		this.ngaynhap = ngaynhap;
	}

}
