package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Chucvu generated by hbm2java
 */
@Entity
@Table(name = "chucvu", catalog = "dienthoai")
public class Chucvu implements java.io.Serializable {

	private Integer id;
	private String tenchucvu;
	private Set<ChucvuNguoidung> chucvuNguoidungs = new HashSet<ChucvuNguoidung>(0);

	public Chucvu() {
	}

	public Chucvu(String tenchucvu) {
		this.tenchucvu = tenchucvu;
	}

	public Chucvu(String tenchucvu, Set<ChucvuNguoidung> chucvuNguoidungs) {
		this.tenchucvu = tenchucvu;
		this.chucvuNguoidungs = chucvuNguoidungs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "tenchucvu", nullable = false, length = 100)
	public String getTenchucvu() {
		return this.tenchucvu;
	}

	public void setTenchucvu(String tenchucvu) {
		this.tenchucvu = tenchucvu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chucvu")
	public Set<ChucvuNguoidung> getChucvuNguoidungs() {
		return this.chucvuNguoidungs;
	}

	public void setChucvuNguoidungs(Set<ChucvuNguoidung> chucvuNguoidungs) {
		this.chucvuNguoidungs = chucvuNguoidungs;
	}

}
