package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Dienthoai generated by hbm2java
 */
@Entity
@Table(name = "dienthoai", catalog = "dienthoai")
public class Dienthoai implements java.io.Serializable {

	private Integer idDt;
	private DmHdh dmHdh;
	private DmManhinh dmManhinh;
	private Hinhanhdt hinhanhdt;
	private Mucgia mucgia;
	private Thuonghieu thuonghieu;
	private String tenDt;
	private String giaban;
	private Set<Binhluan> binhluans = new HashSet<Binhluan>(0);
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);
	private Set<Chitietkm> chitietkms = new HashSet<Chitietkm>(0);
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public Dienthoai() {
	}

	public Dienthoai(DmHdh dmHdh, DmManhinh dmManhinh, Hinhanhdt hinhanhdt, Mucgia mucgia, Thuonghieu thuonghieu,
			String tenDt, String giaban) {
		this.dmHdh = dmHdh;
		this.dmManhinh = dmManhinh;
		this.hinhanhdt = hinhanhdt;
		this.mucgia = mucgia;
		this.thuonghieu = thuonghieu;
		this.tenDt = tenDt;
		this.giaban = giaban;
	}

	public Dienthoai(DmHdh dmHdh, DmManhinh dmManhinh, Hinhanhdt hinhanhdt, Mucgia mucgia, Thuonghieu thuonghieu,
			String tenDt, String giaban, Set<Binhluan> binhluans, Set<Chitiethoadon> chitiethoadons,
			Set<Chitietkm> chitietkms, Set<Chitietdt> chitietdts) {
		this.dmHdh = dmHdh;
		this.dmManhinh = dmManhinh;
		this.hinhanhdt = hinhanhdt;
		this.mucgia = mucgia;
		this.thuonghieu = thuonghieu;
		this.tenDt = tenDt;
		this.giaban = giaban;
		this.binhluans = binhluans;
		this.chitiethoadons = chitiethoadons;
		this.chitietkms = chitietkms;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dt", unique = true, nullable = false)
	public Integer getIdDt() {
		return this.idDt;
	}

	public void setIdDt(Integer idDt) {
		this.idDt = idDt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dmhdh", nullable = false)
	public DmHdh getDmHdh() {
		return this.dmHdh;
	}

	public void setDmHdh(DmHdh dmHdh) {
		this.dmHdh = dmHdh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_dmmanhinh", nullable = false)
	public DmManhinh getDmManhinh() {
		return this.dmManhinh;
	}

	public void setDmManhinh(DmManhinh dmManhinh) {
		this.dmManhinh = dmManhinh;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_hinhanhdt", nullable = false)
	public Hinhanhdt getHinhanhdt() {
		return this.hinhanhdt;
	}

	public void setHinhanhdt(Hinhanhdt hinhanhdt) {
		this.hinhanhdt = hinhanhdt;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_mucgia", nullable = false)
	public Mucgia getMucgia() {
		return this.mucgia;
	}

	public void setMucgia(Mucgia mucgia) {
		this.mucgia = mucgia;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_thuonghieu", nullable = false)
	public Thuonghieu getThuonghieu() {
		return this.thuonghieu;
	}

	public void setThuonghieu(Thuonghieu thuonghieu) {
		this.thuonghieu = thuonghieu;
	}

	@Column(name = "ten_dt", nullable = false, length = 50)
	public String getTenDt() {
		return this.tenDt;
	}

	public void setTenDt(String tenDt) {
		this.tenDt = tenDt;
	}

	@Column(name = "giaban", nullable = false, length = 200)
	public String getGiaban() {
		return this.giaban;
	}

	public void setGiaban(String giaban) {
		this.giaban = giaban;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienthoai")
	public Set<Binhluan> getBinhluans() {
		return this.binhluans;
	}

	public void setBinhluans(Set<Binhluan> binhluans) {
		this.binhluans = binhluans;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienthoai")
	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienthoai")
	public Set<Chitietkm> getChitietkms() {
		return this.chitietkms;
	}

	public void setChitietkms(Set<Chitietkm> chitietkms) {
		this.chitietkms = chitietkms;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dienthoai")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
