package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DmHdh generated by hbm2java
 */
@Entity
@Table(name = "dm_hdh", catalog = "dienthoai")
public class DmHdh implements java.io.Serializable {

	private Integer idDmHdh;
	private String tenDmHdh;
	private Set<Dienthoai> dienthoais = new HashSet<Dienthoai>(0);

	public DmHdh() {
	}

	public DmHdh(String tenDmHdh) {
		this.tenDmHdh = tenDmHdh;
	}

	public DmHdh(String tenDmHdh, Set<Dienthoai> dienthoais) {
		this.tenDmHdh = tenDmHdh;
		this.dienthoais = dienthoais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_dm_hdh", unique = true, nullable = false)
	public Integer getIdDmHdh() {
		return this.idDmHdh;
	}

	public void setIdDmHdh(Integer idDmHdh) {
		this.idDmHdh = idDmHdh;
	}

	@Column(name = "ten_dm_hdh", nullable = false, length = 100)
	public String getTenDmHdh() {
		return this.tenDmHdh;
	}

	public void setTenDmHdh(String tenDmHdh) {
		this.tenDmHdh = tenDmHdh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dmHdh")
	public Set<Dienthoai> getDienthoais() {
		return this.dienthoais;
	}

	public void setDienthoais(Set<Dienthoai> dienthoais) {
		this.dienthoais = dienthoais;
	}

}
