package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hedieuhanh generated by hbm2java
 */
@Entity
@Table(name = "hedieuhanh", catalog = "dienthoai")
public class Hedieuhanh implements java.io.Serializable {

	private Integer idHdh;
	private String tenHdh;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public Hedieuhanh() {
	}

	public Hedieuhanh(String tenHdh) {
		this.tenHdh = tenHdh;
	}

	public Hedieuhanh(String tenHdh, Set<Chitietdt> chitietdts) {
		this.tenHdh = tenHdh;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hdh", unique = true, nullable = false)
	public Integer getIdHdh() {
		return this.idHdh;
	}

	public void setIdHdh(Integer idHdh) {
		this.idHdh = idHdh;
	}

	@Column(name = "ten_hdh", nullable = false, length = 50)
	public String getTenHdh() {
		return this.tenHdh;
	}

	public void setTenHdh(String tenHdh) {
		this.tenHdh = tenHdh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hedieuhanh")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
