package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hinhanhdt generated by hbm2java
 */
@Entity
@Table(name = "hinhanhdt", catalog = "dienthoai")
public class Hinhanhdt implements java.io.Serializable {

	private Integer idHinhanhdt;
	private String tenHinhanhdt;
	private Set<Dienthoai> dienthoais = new HashSet<Dienthoai>(0);

	public Hinhanhdt() {
	}

	public Hinhanhdt(String tenHinhanhdt) {
		this.tenHinhanhdt = tenHinhanhdt;
	}

	public Hinhanhdt(String tenHinhanhdt, Set<Dienthoai> dienthoais) {
		this.tenHinhanhdt = tenHinhanhdt;
		this.dienthoais = dienthoais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hinhanhdt", unique = true, nullable = false)
	public Integer getIdHinhanhdt() {
		return this.idHinhanhdt;
	}

	public void setIdHinhanhdt(Integer idHinhanhdt) {
		this.idHinhanhdt = idHinhanhdt;
	}

	@Column(name = "ten_hinhanhdt", nullable = false, length = 200)
	public String getTenHinhanhdt() {
		return this.tenHinhanhdt;
	}

	public void setTenHinhanhdt(String tenHinhanhdt) {
		this.tenHinhanhdt = tenHinhanhdt;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hinhanhdt")
	public Set<Dienthoai> getDienthoais() {
		return this.dienthoais;
	}

	public void setDienthoais(Set<Dienthoai> dienthoais) {
		this.dienthoais = dienthoais;
	}

}
