package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Hoadon generated by hbm2java
 */
@Entity
@Table(name = "hoadon", catalog = "dienthoai")
public class Hoadon implements java.io.Serializable {

	private Integer idHoadon;
	private String tenKhachhang;
	private String diachi;
	private String sdt;
	private Date ngaylap;
	private boolean trangthai;
	private String tongtien;
	private Set<Chitiethoadon> chitiethoadons = new HashSet<Chitiethoadon>(0);

	public Hoadon() {
	}

	public Hoadon(String tenKhachhang, String diachi, String sdt, Date ngaylap, boolean trangthai, String tongtien) {
		this.tenKhachhang = tenKhachhang;
		this.diachi = diachi;
		this.sdt = sdt;
		this.ngaylap = ngaylap;
		this.trangthai = trangthai;
		this.tongtien = tongtien;
	}

	public Hoadon(String tenKhachhang, String diachi, String sdt, Date ngaylap, boolean trangthai, String tongtien,
			Set<Chitiethoadon> chitiethoadons) {
		this.tenKhachhang = tenKhachhang;
		this.diachi = diachi;
		this.sdt = sdt;
		this.ngaylap = ngaylap;
		this.trangthai = trangthai;
		this.tongtien = tongtien;
		this.chitiethoadons = chitiethoadons;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hoadon", unique = true, nullable = false)
	public Integer getIdHoadon() {
		return this.idHoadon;
	}

	public void setIdHoadon(Integer idHoadon) {
		this.idHoadon = idHoadon;
	}

	@Column(name = "ten_khachhang", nullable = false, length = 100)
	public String getTenKhachhang() {
		return this.tenKhachhang;
	}

	public void setTenKhachhang(String tenKhachhang) {
		this.tenKhachhang = tenKhachhang;
	}

	@Column(name = "diachi", nullable = false, length = 200)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "sdt", nullable = false, length = 50)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaylap", nullable = false, length = 10)
	public Date getNgaylap() {
		return this.ngaylap;
	}

	public void setNgaylap(Date ngaylap) {
		this.ngaylap = ngaylap;
	}

	@Column(name = "trangthai", nullable = false)
	public boolean isTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(boolean trangthai) {
		this.trangthai = trangthai;
	}

	@Column(name = "tongtien", nullable = false, length = 200)
	public String getTongtien() {
		return this.tongtien;
	}

	public void setTongtien(String tongtien) {
		this.tongtien = tongtien;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hoadon")
	public Set<Chitiethoadon> getChitiethoadons() {
		return this.chitiethoadons;
	}

	public void setChitiethoadons(Set<Chitiethoadon> chitiethoadons) {
		this.chitiethoadons = chitiethoadons;
	}

}
