package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Khuyenmai generated by hbm2java
 */
@Entity
@Table(name = "khuyenmai", catalog = "dienthoai")
public class Khuyenmai implements java.io.Serializable {

	private Integer idKhuyenmai;
	private int tenKm;
	private Date ngaybatdau;
	private Date ngayketthuc;
	private Set<Chitietkm> chitietkms = new HashSet<Chitietkm>(0);

	public Khuyenmai() {
	}

	public Khuyenmai(int tenKm, Date ngaybatdau, Date ngayketthuc) {
		this.tenKm = tenKm;
		this.ngaybatdau = ngaybatdau;
		this.ngayketthuc = ngayketthuc;
	}

	public Khuyenmai(int tenKm, Date ngaybatdau, Date ngayketthuc, Set<Chitietkm> chitietkms) {
		this.tenKm = tenKm;
		this.ngaybatdau = ngaybatdau;
		this.ngayketthuc = ngayketthuc;
		this.chitietkms = chitietkms;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_khuyenmai", unique = true, nullable = false)
	public Integer getIdKhuyenmai() {
		return this.idKhuyenmai;
	}

	public void setIdKhuyenmai(Integer idKhuyenmai) {
		this.idKhuyenmai = idKhuyenmai;
	}

	@Column(name = "ten_km", nullable = false)
	public int getTenKm() {
		return this.tenKm;
	}

	public void setTenKm(int tenKm) {
		this.tenKm = tenKm;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngaybatdau", nullable = false, length = 10)
	public Date getNgaybatdau() {
		return this.ngaybatdau;
	}

	public void setNgaybatdau(Date ngaybatdau) {
		this.ngaybatdau = ngaybatdau;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngayketthuc", nullable = false, length = 10)
	public Date getNgayketthuc() {
		return this.ngayketthuc;
	}

	public void setNgayketthuc(Date ngayketthuc) {
		this.ngayketthuc = ngayketthuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "khuyenmai")
	public Set<Chitietkm> getChitietkms() {
		return this.chitietkms;
	}

	public void setChitietkms(Set<Chitietkm> chitietkms) {
		this.chitietkms = chitietkms;
	}

}
