package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Manhinh generated by hbm2java
 */
@Entity
@Table(name = "manhinh", catalog = "dienthoai")
public class Manhinh implements java.io.Serializable {

	private Integer idMh;
	private String cnMh;
	private String mauMh;
	private String chuanMh;
	private String dophangiaiMh;
	private String cnCamung;
	private String matkinhMh;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public Manhinh() {
	}

	public Manhinh(String cnMh, String mauMh, String chuanMh, String dophangiaiMh, String cnCamung, String matkinhMh) {
		this.cnMh = cnMh;
		this.mauMh = mauMh;
		this.chuanMh = chuanMh;
		this.dophangiaiMh = dophangiaiMh;
		this.cnCamung = cnCamung;
		this.matkinhMh = matkinhMh;
	}

	public Manhinh(String cnMh, String mauMh, String chuanMh, String dophangiaiMh, String cnCamung, String matkinhMh,
			Set<Chitietdt> chitietdts) {
		this.cnMh = cnMh;
		this.mauMh = mauMh;
		this.chuanMh = chuanMh;
		this.dophangiaiMh = dophangiaiMh;
		this.cnCamung = cnCamung;
		this.matkinhMh = matkinhMh;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_mh", unique = true, nullable = false)
	public Integer getIdMh() {
		return this.idMh;
	}

	public void setIdMh(Integer idMh) {
		this.idMh = idMh;
	}

	@Column(name = "cn_mh", nullable = false, length = 100)
	public String getCnMh() {
		return this.cnMh;
	}

	public void setCnMh(String cnMh) {
		this.cnMh = cnMh;
	}

	@Column(name = "mau_mh", nullable = false, length = 100)
	public String getMauMh() {
		return this.mauMh;
	}

	public void setMauMh(String mauMh) {
		this.mauMh = mauMh;
	}

	@Column(name = "chuan_mh", nullable = false, length = 100)
	public String getChuanMh() {
		return this.chuanMh;
	}

	public void setChuanMh(String chuanMh) {
		this.chuanMh = chuanMh;
	}

	@Column(name = "dophangiai_mh", nullable = false, length = 100)
	public String getDophangiaiMh() {
		return this.dophangiaiMh;
	}

	public void setDophangiaiMh(String dophangiaiMh) {
		this.dophangiaiMh = dophangiaiMh;
	}

	@Column(name = "cn_camung", nullable = false, length = 100)
	public String getCnCamung() {
		return this.cnCamung;
	}

	public void setCnCamung(String cnCamung) {
		this.cnCamung = cnCamung;
	}

	@Column(name = "matkinh_mh", nullable = false, length = 100)
	public String getMatkinhMh() {
		return this.matkinhMh;
	}

	public void setMatkinhMh(String matkinhMh) {
		this.matkinhMh = matkinhMh;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "manhinh")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
