package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mucgia generated by hbm2java
 */
@Entity
@Table(name = "mucgia", catalog = "dienthoai")
public class Mucgia implements java.io.Serializable {

	private Integer idMucgia;
	private String tenMucgia;
	private Set<Dienthoai> dienthoais = new HashSet<Dienthoai>(0);

	public Mucgia() {
	}

	public Mucgia(String tenMucgia) {
		this.tenMucgia = tenMucgia;
	}

	public Mucgia(String tenMucgia, Set<Dienthoai> dienthoais) {
		this.tenMucgia = tenMucgia;
		this.dienthoais = dienthoais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_mucgia", unique = true, nullable = false)
	public Integer getIdMucgia() {
		return this.idMucgia;
	}

	public void setIdMucgia(Integer idMucgia) {
		this.idMucgia = idMucgia;
	}

	@Column(name = "ten_mucgia", nullable = false, length = 100)
	public String getTenMucgia() {
		return this.tenMucgia;
	}

	public void setTenMucgia(String tenMucgia) {
		this.tenMucgia = tenMucgia;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "mucgia")
	public Set<Dienthoai> getDienthoais() {
		return this.dienthoais;
	}

	public void setDienthoais(Set<Dienthoai> dienthoais) {
		this.dienthoais = dienthoais;
	}

}
