package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;

/**
 * Nguoidung generated by hbm2java
 */
@Entity
@Table(name = "nguoidung", catalog = "dienthoai")
public class Nguoidung implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer idNguoidung;
	private String tenNguoidung;
	private String gmail;
	private boolean gioitinh;
	private String diachi;
	private String hinhanh;
	private String matkhau;	
	private Set<ChucvuNguoidung> chucvuNguoidungs = new HashSet<ChucvuNguoidung>(0);

	public Nguoidung() {
	}

	public Nguoidung(String tenNguoidung, String gmail, boolean gioitinh, String diachi, String hinhanh,String matkhau) {
		this.tenNguoidung = tenNguoidung;
		this.gmail = gmail;
		this.gioitinh = gioitinh;
		this.diachi = diachi;
		this.hinhanh = hinhanh;
		this.matkhau = matkhau;
	}

	public Nguoidung(String tenNguoidung, String gmail, boolean gioitinh, String diachi, String hinhanh,String matkhau,
			Set<ChucvuNguoidung> chucvuNguoidungs) {
		this.tenNguoidung = tenNguoidung;
		this.gmail = gmail;
		this.gioitinh = gioitinh;
		this.diachi = diachi;
		this.hinhanh = hinhanh;
		this.matkhau = matkhau;
		this.chucvuNguoidungs = chucvuNguoidungs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_nguoidung", unique = true, nullable = false)
	public Integer getIdNguoidung() {
		return this.idNguoidung;
	}

	public void setIdNguoidung(Integer idNguoidung) {
		this.idNguoidung = idNguoidung;
	}

	@Column(name = "ten_nguoidung", nullable = false, length = 100)
	public String getTenNguoidung() {
		return this.tenNguoidung;
	}

	public void setTenNguoidung(String tenNguoidung) {
		this.tenNguoidung = tenNguoidung;
	}

	@Column(name = "gmail", nullable = false, length = 100)
	public String getGmail() {
		return this.gmail;
	}

	public void setGmail(String gmail) {
		this.gmail = gmail;
	}

	@Column(name = "gioitinh", nullable = false)
	public boolean isGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(boolean gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Column(name = "diachi", nullable = false, length = 100)
	public String getDiachi() {
		return this.diachi;
	}

	public void setDiachi(String diachi) {
		this.diachi = diachi;
	}

	@Column(name = "hinhanh", nullable = false, length = 200)
	public String getHinhanh() {
		return this.hinhanh;
	}

	public void setHinhanh(String hinhanh) {
		this.hinhanh = hinhanh;
	}

	@Column(name = "matkhau", nullable = false, length = 200)
	public String getMatkhau() {
		return this.matkhau;
	}

	public void setMatkhau(String matkhau) {
		this.matkhau = matkhau;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "nguoidung")
	public Set<ChucvuNguoidung> getChucvuNguoidungs() {
		return this.chucvuNguoidungs;
	}

	public void setChucvuNguoidungs(Set<ChucvuNguoidung> chucvuNguoidungs) {
		this.chucvuNguoidungs = chucvuNguoidungs;
	}

	 
}
