package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ThietkeTrongluong generated by hbm2java
 */
@Entity
@Table(name = "thietke_trongluong", catalog = "dienthoai")
public class ThietkeTrongluong implements java.io.Serializable {

	private Integer idTkTl;
	private String kieudang;
	private String chatlieu;
	private String kichthuoc;
	private String trongluong;
	private String chongnuoc;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public ThietkeTrongluong() {
	}

	public ThietkeTrongluong(String kieudang, String chatlieu, String kichthuoc, String trongluong, String chongnuoc) {
		this.kieudang = kieudang;
		this.chatlieu = chatlieu;
		this.kichthuoc = kichthuoc;
		this.trongluong = trongluong;
		this.chongnuoc = chongnuoc;
	}

	public ThietkeTrongluong(String kieudang, String chatlieu, String kichthuoc, String trongluong, String chongnuoc,
			Set<Chitietdt> chitietdts) {
		this.kieudang = kieudang;
		this.chatlieu = chatlieu;
		this.kichthuoc = kichthuoc;
		this.trongluong = trongluong;
		this.chongnuoc = chongnuoc;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_tk_tl", unique = true, nullable = false)
	public Integer getIdTkTl() {
		return this.idTkTl;
	}

	public void setIdTkTl(Integer idTkTl) {
		this.idTkTl = idTkTl;
	}

	@Column(name = "kieudang", nullable = false, length = 100)
	public String getKieudang() {
		return this.kieudang;
	}

	public void setKieudang(String kieudang) {
		this.kieudang = kieudang;
	}

	@Column(name = "chatlieu", nullable = false, length = 100)
	public String getChatlieu() {
		return this.chatlieu;
	}

	public void setChatlieu(String chatlieu) {
		this.chatlieu = chatlieu;
	}

	@Column(name = "kichthuoc", nullable = false, length = 100)
	public String getKichthuoc() {
		return this.kichthuoc;
	}

	public void setKichthuoc(String kichthuoc) {
		this.kichthuoc = kichthuoc;
	}

	@Column(name = "trongluong", nullable = false, length = 100)
	public String getTrongluong() {
		return this.trongluong;
	}

	public void setTrongluong(String trongluong) {
		this.trongluong = trongluong;
	}

	@Column(name = "chongnuoc", nullable = false, length = 100)
	public String getChongnuoc() {
		return this.chongnuoc;
	}

	public void setChongnuoc(String chongnuoc) {
		this.chongnuoc = chongnuoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thietkeTrongluong")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
