package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thongtinpin generated by hbm2java
 */
@Entity
@Table(name = "thongtinpin", catalog = "dienthoai")
public class Thongtinpin implements java.io.Serializable {

	private Integer idThongtin;
	private String loaipin;
	private String duongluong;
	private String thoaroi;
	private Set<Chitietdt> chitietdts = new HashSet<Chitietdt>(0);

	public Thongtinpin() {
	}

	public Thongtinpin(String loaipin, String duongluong, String thoaroi) {
		this.loaipin = loaipin;
		this.duongluong = duongluong;
		this.thoaroi = thoaroi;
	}

	public Thongtinpin(String loaipin, String duongluong, String thoaroi, Set<Chitietdt> chitietdts) {
		this.loaipin = loaipin;
		this.duongluong = duongluong;
		this.thoaroi = thoaroi;
		this.chitietdts = chitietdts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_thongtin", unique = true, nullable = false)
	public Integer getIdThongtin() {
		return this.idThongtin;
	}

	public void setIdThongtin(Integer idThongtin) {
		this.idThongtin = idThongtin;
	}

	@Column(name = "loaipin", nullable = false, length = 50)
	public String getLoaipin() {
		return this.loaipin;
	}

	public void setLoaipin(String loaipin) {
		this.loaipin = loaipin;
	}

	@Column(name = "duongluong", nullable = false, length = 50)
	public String getDuongluong() {
		return this.duongluong;
	}

	public void setDuongluong(String duongluong) {
		this.duongluong = duongluong;
	}

	@Column(name = "thoaroi", nullable = false, length = 50)
	public String getThoaroi() {
		return this.thoaroi;
	}

	public void setThoaroi(String thoaroi) {
		this.thoaroi = thoaroi;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thongtinpin")
	public Set<Chitietdt> getChitietdts() {
		return this.chitietdts;
	}

	public void setChitietdts(Set<Chitietdt> chitietdts) {
		this.chitietdts = chitietdts;
	}

}
