package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Thuonghieu generated by hbm2java
 */
@Entity
@Table(name = "thuonghieu", catalog = "dienthoai")
public class Thuonghieu implements java.io.Serializable {

	private Integer idThuonghieu;
	private String tenThuonghieu;
	private Set<Dienthoai> dienthoais = new HashSet<Dienthoai>(0);

	public Thuonghieu() {
	}

	public Thuonghieu(String tenThuonghieu) {
		this.tenThuonghieu = tenThuonghieu;
	}

	public Thuonghieu(String tenThuonghieu, Set<Dienthoai> dienthoais) {
		this.tenThuonghieu = tenThuonghieu;
		this.dienthoais = dienthoais;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_thuonghieu", unique = true, nullable = false)
	public Integer getIdThuonghieu() {
		return this.idThuonghieu;
	}

	public void setIdThuonghieu(Integer idThuonghieu) {
		this.idThuonghieu = idThuonghieu;
	}

	@Column(name = "ten_thuonghieu", nullable = false, length = 100)
	public String getTenThuonghieu() {
		return this.tenThuonghieu;
	}

	public void setTenThuonghieu(String tenThuonghieu) {
		this.tenThuonghieu = tenThuonghieu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "thuonghieu")
	public Set<Dienthoai> getDienthoais() {
		return this.dienthoais;
	}

	public void setDienthoais(Set<Dienthoai> dienthoais) {
		this.dienthoais = dienthoais;
	}

}
