package com.java.phone.entities;
// Generated Jul 19, 2018 3:39:19 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TraloiBl generated by hbm2java
 */
@Entity
@Table(name = "traloi_bl", catalog = "dienthoai")
public class TraloiBl implements java.io.Serializable {

	private Integer idTraloi;
	private Binhluan binhluan;
	private String tenTraloi;
	private int noidung;
	private Date thoigian;

	public TraloiBl() {
	}

	public TraloiBl(Binhluan binhluan, String tenTraloi, int noidung, Date thoigian) {
		this.binhluan = binhluan;
		this.tenTraloi = tenTraloi;
		this.noidung = noidung;
		this.thoigian = thoigian;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_traloi", unique = true, nullable = false)
	public Integer getIdTraloi() {
		return this.idTraloi;
	}

	public void setIdTraloi(Integer idTraloi) {
		this.idTraloi = idTraloi;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_binhluan", nullable = false)
	public Binhluan getBinhluan() {
		return this.binhluan;
	}

	public void setBinhluan(Binhluan binhluan) {
		this.binhluan = binhluan;
	}

	@Column(name = "ten_traloi", nullable = false, length = 50)
	public String getTenTraloi() {
		return this.tenTraloi;
	}

	public void setTenTraloi(String tenTraloi) {
		this.tenTraloi = tenTraloi;
	}

	@Column(name = "noidung", nullable = false)
	public int getNoidung() {
		return this.noidung;
	}

	public void setNoidung(int noidung) {
		this.noidung = noidung;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "thoigian", nullable = false, length = 19)
	public Date getThoigian() {
		return this.thoigian;
	}

	public void setThoigian(Date thoigian) {
		this.thoigian = thoigian;
	}

}
